name: Test

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main

jobs:
  validate: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Validate HTML
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: .
        
  build:
    runs-on: ubuntu-latest
    needs: validate 
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to Github pages
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
